### ISSUE TITLE
使用任意弹射物(箭矢,雪球,鸡蛋,三叉戟)射击实体会出现如下报错

### ISSUE THREAD

**Issue by Yurium7** [PQguanfang/MythicLibreforge#3]
[22:37:55 ERROR]: Could not pass event EntityDamageByEntityEvent to libreforge v4.46.0
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R1.entity.CraftTippedArrow cannot be cast to class org.bukkit.entity.LivingEntity (org.bukkit.craftbukkit.v1_20_R1.entity.CraftTippedArrow and org.bukkit.entity.LivingEntity are in unnamed module of loader java.net.URLClassLoader @442d9b6e)
        at cn.superiormc.mythiclibreforge.triggers.TriggerHighestAttack.handle(TriggerHighestAttack.java:47) ~[[E][ECO属性注册]MythicLibreforge-1.2.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2319.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2062]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:264) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1227) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1080) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1023) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1261) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2260) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1479) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:355) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:403) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:233) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:224) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:297) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:233) ~[?:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1435) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:896) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:873) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1585) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by PQguanfang** [comment]
请不要滥用issues，明明一个地方可以继续回复的还要重复开启新的issue。
另外，插件介绍中已明确标注highest_attack是我私用的东西，不受支持，这是最后一次为此修复，再有问题自行解决。
